# Generated by Django 2.2 on 2022-10-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Description', models.CharField(max_length=2048)),
                ('Created_By', models.CharField(max_length=256)),
                ('Created_At', models.DateTimeField()),
                ('Updated_At', models.DateTimeField()),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.IntegerField()),
                ('Password', models.CharField(max_length=15)),
                ('Department', models.CharField(max_length=2048)),
                ('Role', models.CharField(max_length=256)),
                ('Created_By', models.CharField(max_length=256)),
                ('Created_At', models.DateTimeField()),
                ('Updated_At', models.DateTimeField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
